-- Generated by Oracle SQL Developer Data Modeler 20.2.0.167.1538
--   at:        2021-03-13 20:15:32 CET
--   site:      SQL Server 2012
--   type:      SQL Server 2012

USE master
GO

alter database TiendaDeInstrumentos set single_user with rollback immediate
GO

DROP DATABASE IF EXISTS TiendaDeInstrumentos
GO

CREATE DATABASE TiendaDeInstrumentos
ON PRIMARY
( NAME = FG1_dat,
FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\FG1_dat.mdf',
SIZE = 10,
MAXSIZE = 50,
FILEGROWTH = 15% ),
( NAME = FG2_dat,
FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\FG2_dat.ndf',
SIZE = 10,
MAXSIZE = 50,
FILEGROWTH = 15% ),
FILEGROUP FGGrupo1
( NAME = FGGrupo1File1_dat,
FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\FGGrupo1File1.ndf',
SIZE = 10,
MAXSIZE = 50,
FILEGROWTH = 5 ),
( NAME = FGGroup1File2_dat,
FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\FGGroup1File2.ndf',
SIZE = 10,
MAXSIZE = 50,
FILEGROWTH = 5 ),
FILEGROUP FGGrupo2
( NAME = FGGrupo2File1_dat,
FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\FGGrupo2File1_dat.ndf',
SIZE = 10,
MAXSIZE = 50,
FILEGROWTH = 5 ),
( NAME = FGGrupo2File2_dat,
FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\FGGrupo2File2_dat.ndf',
SIZE = 10,
MAXSIZE = 50,
FILEGROWTH = 5 )
LOG ON
( NAME = FG_log,
FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\FG_log.ldf',
SIZE = 5MB,
MAXSIZE = 25MB,
FILEGROWTH = 5MB ) ;
GO 



USE TiendaDeInstrumentos

DROP TABLE IF EXISTS FamiliaReparadores
GO
DROP TABLE IF EXISTS Reparadores
GO
DROP TABLE IF EXISTS VendedoresProducto
GO
DROP TABLE IF EXISTS Vendedores
GO
DROP TABLE IF EXISTS Producto
GO
DROP TABLE IF EXISTS Marca
GO
DROP TABLE IF EXISTS PaisFabricacion
GO
DROP TABLE IF EXISTS ContinenteFabricacion
GO
DROP TABLE IF EXISTS Familia
GO






CREATE TABLE ContinenteFabricacion 
    (
	ID uniqueidentifier NOT NULL , 
    Nombre VARCHAR (50) NOT NULL 
    )
GO

ALTER TABLE ContinenteFabricacion ADD CONSTRAINT ContinenteFabricacion_PK PRIMARY KEY CLUSTERED (ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO



CREATE TABLE Familia 
    (
	ID uniqueidentifier NOT NULL ,  
    Nombre VARCHAR(50) NOT NULL 
    )
GO

ALTER TABLE Familia ADD CONSTRAINT Familia_PK PRIMARY KEY CLUSTERED (ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO



CREATE TABLE FamiliaReparadores 
    (
     Reparadores_ID uniqueidentifier NOT NULL , 
     Familia_ID uniqueidentifier NOT NULL 
    )
GO

ALTER TABLE FamiliaReparadores ADD CONSTRAINT Relation_8_PK PRIMARY KEY CLUSTERED (Reparadores_ID, Familia_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO




CREATE TABLE Marca 
    (
     ID uniqueidentifier NOT NULL , 
     Nombre VARCHAR (50) NOT NULL , 
     PaisFabricacion_ID uniqueidentifier NOT NULL 
    )
GO

ALTER TABLE Marca ADD CONSTRAINT Marca_PK PRIMARY KEY CLUSTERED (ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO



CREATE TABLE PaisFabricacion 
    (
     ID uniqueidentifier NOT NULL , 
     Nombre VARCHAR (50) NOT NULL , 
     ContinenteFabricacion_ID uniqueidentifier NOT NULL 
    )
GO

ALTER TABLE PaisFabricacion ADD CONSTRAINT PaisFabricacion_PK PRIMARY KEY CLUSTERED (ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO



CREATE TABLE Producto 
    (
     ID uniqueidentifier NOT NULL , 
     Nombre VARCHAR (50) NOT NULL , 
     Precio BIGINT NOT NULL , 
     Tipo VARCHAR (50) NOT NULL , 
     Marca_ID uniqueidentifier NOT NULL , 
     Familia_ID uniqueidentifier NOT NULL 
    )
GO

ALTER TABLE Producto ADD CONSTRAINT Producto_PK PRIMARY KEY CLUSTERED (ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO



CREATE TABLE Reparadores 
    (
     ID uniqueidentifier NOT NULL ,  
     Nombre VARCHAR (50) NOT NULL , 
     Salario BIGINT NOT NULL , 
     Puesto VARCHAR (50) NOT NULL 
    )
GO

ALTER TABLE Reparadores ADD CONSTRAINT Reparadores_PK PRIMARY KEY CLUSTERED (ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO



CREATE TABLE Vendedores 
    (
     ID uniqueidentifier NOT NULL , 
     Nombre VARCHAR (50) NOT NULL , 
     Salario BIGINT NOT NULL 
    )
GO

ALTER TABLE Vendedores ADD CONSTRAINT Vendedores_PK PRIMARY KEY CLUSTERED (ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO



CREATE TABLE VendedoresProducto 
    (
     Producto_ID uniqueidentifier NOT NULL , 
     Vendedores_ID uniqueidentifier NOT NULL 
    )
GO

ALTER TABLE VendedoresProducto ADD CONSTRAINT Relation_6_PK PRIMARY KEY CLUSTERED (Producto_ID, Vendedores_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

ALTER TABLE Marca 
    ADD CONSTRAINT Marca_PaisFabricacion_FK FOREIGN KEY 
    ( 
     PaisFabricacion_ID
    ) 
    REFERENCES PaisFabricacion 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE PaisFabricacion 
    ADD CONSTRAINT PaisFabricacion_ContinenteFabricacion_FK FOREIGN KEY 
    ( 
     ContinenteFabricacion_ID
    ) 
    REFERENCES ContinenteFabricacion 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Producto 
    ADD CONSTRAINT Producto_Familia_FK FOREIGN KEY 
    ( 
     Familia_ID
    ) 
    REFERENCES Familia 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Producto 
    ADD CONSTRAINT Producto_Marca_FK FOREIGN KEY 
    ( 
     Marca_ID
    ) 
    REFERENCES Marca 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE VendedoresProducto 
    ADD CONSTRAINT Relation_6_Producto_FK FOREIGN KEY 
    ( 
     Producto_ID
    ) 
    REFERENCES Producto 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE VendedoresProducto 
    ADD CONSTRAINT Relation_6_Vendedores_FK FOREIGN KEY 
    ( 
     Vendedores_ID
    ) 
    REFERENCES Vendedores 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE FamiliaReparadores 
    ADD CONSTRAINT Relation_8_Familia_FK FOREIGN KEY 
    ( 
     Familia_ID
    ) 
    REFERENCES Familia 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE FamiliaReparadores 
    ADD CONSTRAINT Relation_8_Reparadores_FK FOREIGN KEY 
    ( 
     Reparadores_ID
    ) 
    REFERENCES Reparadores 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO
--Añadido para Particiones

DROP TABLE IF EXISTS EnReparacion
GO

CREATE TABLE EnReparacion 
    (
     ID UNIQUEIDENTIFIER NOT NULL , 
     Nombre VARCHAR (50) NOT NULL , 
     F_Iniicio DATETIME NOT NULL , 
     F_Final DATETIME NOT NULL , 
     Reparadores_ID UNIQUEIDENTIFIER NOT NULL 
    )
GO

ALTER TABLE EnReparacion ADD CONSTRAINT EnReparacion_PK PRIMARY KEY CLUSTERED (ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

ALTER TABLE EnReparacion 
    ADD CONSTRAINT EnReparacion_Reparadores_FK FOREIGN KEY 
    ( 
     Reparadores_ID
    ) 
    REFERENCES Reparadores 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             9
-- CREATE INDEX                             0
-- ALTER TABLE                             17
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE SCHEMA                            0
-- CREATE SEQUENCE                          0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0

